cookie/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.create, name='cookie.create'),
    path('read/', views.read, name='cookie.read'),
    path('update/<int:cookieId>', views.update, name='cookie.update'),
    path('delete/<int:cookieId>', views.delete, name='cookie.delete')
]

mysite/urls.py
from mysite import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('cookie/', include('cookie.urls'))
]


if settings.DEBUG:
    urlpatterns += settings.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', views.register, name="register"),
    path('profile', views.profile, name='profile')
]


# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

cookie/models.py
from django.db import models


# Create your models here.
class Cookie(models.Model):
    title = models.CharField(max_length=255, null=False)
    name = models.CharField(max_length=255, null=False)
    price = models.DecimalField(max_digits=10, default=0, decimal_places=2)
    serial = models.CharField(max_length=1024, unique=True, null=False)
    body = models.TextField()
    image = models.ImageField(upload_to='media/images/cookie')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

user/models.py
from django.db import models

# Create your models here.

cookie/forms.py
from django.db.models import fields
from .models import Cookie 
from django import forms

class CookieForm(forms.ModelForm):
    class Meta:
        model = Cookie
        fields = ['title', 'name', 'price', 'serial', 'body', 'image']

cookie/views.py
from django.shortcuts import render
from .forms import CookieForm
from .models import Cookie
# Create your views here.
from django.contrib.auth.models import AbstractBaseUser

def create(request):
    if request.method == "POST":
        form = CookieForm(request.POST)
        if form.is_valid(): 
            form.save()
    return render(request, 'cookie/create.html')

def read(request):
    cookies = Cookie.objects.all()
    return render(request, {'cookies': cookies})

def update(request, cookieId):
    cookie = Cookie.objects.get(id=cookieId)
    if request.method == "POST":
        form = CookieForm(request.POST, request.FILES, instance=cookie)
        if form.is_valid():
            form.save()
    return render(request, 'cookie/update.html', {'cookie': cookie})


def delete(request, cookieId):
    pass

user/views.py
from django.contrib.auth import forms
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render

# Create your views here.

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid(): 
            form.save()
    return render(request, 'registration/register.html')


def profile(request):
    return render(request, 'user/profile.html')

cookie/templates/cookie/create.html
{% extends 'admin/dashboard.html' %}


{% block dashboard %}
    <form action="{% url 'cookie.create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label for="id_title">Title: </label>
            <input type="text" id="id_title", name="title" placeholder="Title..." required>
        </div>
        <br>
        <div>
            <label for="id_name">Name: </label>
            <input type="text" id="id_name", name="name" placeholder="Name..." required>
        </div>
        <br>
        <div>
            <label for="id_price">Price: </label>
            <input type="text" id="id_price", name="price" placeholder="Price..." required>
        </div>
        <br>
        <div>
            <label for="id_serial">Serial: </label>
            <input type="text" id="id_serial", name="serial" placeholder="Serial..." required>
        </div>
        <br>
        <div>
            <label for="id_body">Description: </label>
            <textarea type="text" id="id_body", name="body" placeholder="Description..."></textarea>
        </div>
        <br>
        <div>
            <label for="id_image">Description: </label>
            <input type="text" id="id_image", name="image">
        </div>
        <br>
        <input type="submit" value="Store">
    </form>
{% endblock dashboard %}
    

cookie/templates/cookie/read.html
{% extends 'admin/dashboard.html' %}


{% block dashboard %}
    <ul>
        {% for cookie in cookies %}
        <li>Title is:{{cookie.title}}</li>
        <li>Name is:{{cookie.name}}</li>
        <li>Price is:{{cookie.price}}</li>
        <li>Serial is:{{cookie.serial}}</li>
        <li>Description is:{{cookie.body}}</li>
        <li>Image is: <img src="/{{cookie.image}}"></li>
        {% endfor %}
    </ul>
{% endblock dashboard %}
    

cookie/templates/cookie/show.html
{% extends 'main.html' %}


{% block content %}
    
{% endblock content %}
    

cookie/templates/cookie/update.html
{% extends 'admin/dashboard.html' %}


{% block dashboard %}
    <form action="{% url 'cookie.update' cookie.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label for="id_title">Title: </label>
            <input type="text" id="id_title" name="title", value="{{ cookie.title }}" required>
        </div>
        <div>
            <label for="id_name">Name: </label>
            <input type="text" id="id_name" name="name", value="{{ cookie.name }}" required>
        </div>
    </form>
{% endblock dashboard %}
    

user/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% block content %}
            
    {% endblock content %}
    
</body>
</html>

user/templates/user/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcom to your accont dear {{user.username}}</h1>
    <br>
    <a href="{% url 'logout' %}">Logout</a>
</body>
</html>